eureka:
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762

spring:
  boot:
    admin:
      client:
        url: "http://localhost:5000"